version: "3.8"
services:
        web:
          build: .
          volumes: 
              - ./dittoweb:/var/www/dittoweb.com
              - ./configs/php.ini:/usr/local/etc/php/php.ini
              - ./configs/custom-apache.conf:/etc/apache2/sites-available/custom-apache.conf
          ports:
              - 85:80 